### ISSUE TITLE
how i can use it ?

### ISSUE THREAD

**Issue by gh-darvishani** [hiqdev/yii2-asset-lightbox2#1]
hi ...
how i can using  this light box ?

**Comment by SilverFire** [comment]
Hello!
This Yii2 extension offers only an asset bundle for a [lokesh/lightbox2](https://github.com/lokesh/lightbox2) jQuery plugin.
Please, refer the [Yii2 assets](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html) guide to learn, how to use 3-rd part asset bundles in your project.
