### ISSUE TITLE
sourcePath is not correct

### ISSUE THREAD

**Issue by fullflash** [hiqdev/yii2-asset-lightbox2#2]
add **dist** to the sourcePath parameter in LightboxAsset.php

`public $sourcePath = '@bower/lightbox2/dist/';`

**Comment by SilverFire** [comment]
Fixed by https://github.com/hiqdev/yii2-asset-lightbox2/commit/f082ba006e625456f169b6f3b7f76f23dc5c8703

Thank you

**Comment by SilverFire** [comment]
Bumped [v.2.8.2.2](https://github.com/hiqdev/yii2-asset-lightbox2/releases/tag/2.8.2.2) release
